# Generated by Django 4.2.3 on 2023-07-25 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0003_shelf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shelf',
        ),
    ]
