# Generated by Django 4.2.3 on 2023-07-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_default_image',
            field=models.BooleanField(default=True),
        ),
    ]
