# Generated by Django 4.2.3 on 2023-07-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0008_rename_authors_book_author'),
        ('users_app', '0009_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='books',
            field=models.ManyToManyField(blank=True, to='books_app.book'),
        ),
    ]
