# Generated by Django 4.2.3 on 2023-07-29 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0010_alter_shelf_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shelf', to=settings.AUTH_USER_MODEL),
        ),
    ]
